[project]
name = "up3date"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bpy>=5.2.0",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pytest>=8.0",
    "pytest-cov>=6.0",
    "ruff>=0.16.2",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.coverage.run]
branch = true
omit = [".venv/*", "tests/*"]
source = ["."]

[tool.coverage.report]
fail_under = 95
show_missing = true
skip_covered = true

[tool.ruff.lint]
extend-select = ["ANN", "I", "N"]
ignore = ["ANN401"]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["N999"]
"tests/**" = ["ANN"]

[tool.mypy]
python_version = "3.13"
files = ["__init__.py", "addon.py", "core", "models"]
check_untyped_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["Up3date.addon", "Up3date.core.prop"]
disable_error_code = ["valid-type"]
disallow_any_explicit = true

[[tool.mypy.overrides]]
module = [
    "Up3date.core.blender_types",
    "Up3date.core.material",
    "Up3date.core.operator",
    "Up3date.core.ui",
]
disallow_any_explicit = true
